name: Publish to Comfy registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install patched comfy-cli
        run: pip install --upgrade git+https://github.com/HenkDz/comfy-cli@main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Publish Node
        run: |
          comfy --skip-prompt --no-enable-telemetry env
          comfy node publish --token ${{ secrets.REGISTRY_ACCESS_TOKEN }}
